### ISSUE TITLE
`pubspec.yaml` improvements

### ISSUE THREAD

**Issue by Montana** [beteivap/wasteagram#1]
In newer version of YAML @beteivap , there's a worker that tells the loader/parser what each part of your YAML file converts to actual commands. They’re essentially a collection of `if/then` statements to process human-readable YAML tags into. I'll give you an example below, the YAML Core schema states that both `!!str` my string and my string are equivalent and should be parsed to the same action:

```yaml
definitions: 
  steps:
    - step: &build-test
        name: Build and test
        script:
          - mvn package
        artifacts:
          - target/**
  ```

In this particular example I'm using `maven` general principles still apply. The thing I do when working on Travis CI's `.travis.yml`'s is  tweak the Anchor when called by entering `<<:` I see some of this in this file, but not really being used useful before the Alias. Below this, you can write any desired changes. Mappings are overridden if the new mapping has the same name or is added afterward if different:

```yaml
pipelines:
  branches:
    develop:
      - step: *build-test
    master:
      - step: 
          <<: *build-test
          name: Testing on Master #PaldinOverride
          ongoing: false #PaldinExtension
```

There is a default schema for general-purpose YAML, and many special-use schemas that are each suited for certain niche scenarios. You can even create your own custom schemas or download other user’s schemas on the JSON Schema Store, that being said as this is an example it's not _as_ important when getting into complex YAML situations. Here's an example of a `.travis.yml` file I created for a HashiCorp Terraform integration:

```yaml
dist: focal
language: bash
virt: edge 

git:
  depth: 3

addons:
  apt:
    packages: ['moreutils']

branches:
  only:
    - master
    - /^(cherry-pick-)?backport-\d+-to-/
    
env:
  - tf_version=0.13.2 tf_init_cli_options="-input=false" tf_validation_cli_options=""

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/terraform/d' | tr "\n" ":" | sed "s|::|:|g")
  - exec > >(ts -s '%H:%M:%.S ') 2>&1
  - RANGE1=`echo "$TRAVIS_COMMIT_RANGE" | awk '{n=split($1,a,".");print a[1]}'`
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  
install: 
  - if [[ "${TRAVIS_COMMIT_MESSAGE}" = *"[Build latest]"* ]]; then export BUILD_VERSION="$(cat packaging/version | cut -d'-' -f1,2 | sed -e 's/-/./g').latest"; fi;
  
stages:   

  - name: Montana Mendy's Branching Process

  - name: Nightly operations
    if: branch = master AND type = cron AND env(RUN_NIGHTLY) = yes

  - name: Nightly release
    if: branch = master AND type = cron AND env(RUN_NIGHTLY) = yes
    
  - name: Trigger nightly checks for Terraform updates
    if: branch = master AND type = cron AND env(RUN_NIGHTLY) = yes
    
  - name: Recreate the scheduler 
    if: "((branch IN (master, develop) && type = push) OR branch =~ /.*env.*/ OR commit_message
    =~ /\\[recreate env\\]/) AND commit_message !~ /\\[delete env\\]/ AND type !=
    cron AND commit_message !~ /\\[execute .*. test\\]/ AND commit_message !~ /\\[start
    recreate scheduler\\]/"
    
  - name: Terraform destroy stale clusters
    if: "(type = cron AND branch = develop) OR commit_message =~ /\\[start recreate
    scheduler\\]/ OR commit_message =~ /\\[destroy stale clusters\\]/"
    
  - name: Restart the Montana Mendy branch and execute Terraform tests again if the commit depth goes beyond 5
    if: "((branch IN (master, develop) && type = push) OR branch =~ /.*env.*/ OR commit_message
    =~ /\\[recreate env\\]/) AND commit_message !~ /\\[delete env\\]/ AND type !=
    cron AND commit_message !~ /\\[execute .*. test\\]/ AND commit_message !~ /\\[start
    recreate scheduler\\]/"
    
  - name: Destroy orphaned clusters within Docker to save payload on Terraform and money on Montana's GCP account 
    if: "(type = cron AND branch = develop) OR commit_message =~ /\\[start recreate
    scheduler\\]/ OR commit_message =~ /\\[destroy orphaned clusters\\]/"
    
  - name: Recreate a Terraform instance if there's a cron present or a branch push with --force
    if: "(type = cron AND branch = develop) OR commit_message =~ /\\[start recreate
    scheduler\\]/ OR commit_message =~ /\\[recreate selected clusters\\]/"
    
  - name: Only trigger when a build has passed through Travis and Montana has approved it
    if: >-
      branch = master
      AND type != pull_request
      AND type != cron
      AND tag !~ /(-rc)/
      AND commit_message =~ /\[terraform\travisci/montanamendy* (release candidate|(major|minor|patch) release)\]/   
      
jobs:
  include:
    - stage: Setup Terraform
   ```

You'll see the use of regex here quickly:

```yaml
name: Restart the Montana Mendy branch and execute Terraform tests again if the commit depth goes beyond 5
    if: "((branch IN (master, develop) && type = push) OR branch =~ /.*env.*/ OR commit_message
    =~ /\\[recreate env\\]/) AND commit_message !~ /\\[delete env\\]/ AND type !=
    cron AND commit_message !~ /\\[execute .*. test\\]/ AND commit_message !~ /\\[start
    recreate scheduler\\]/"
```
That's something we can get into as well, other than that good progress Paldin.
